# Python LLM Bias Detector CI/CD Workflow

name: Python LLM Bias Detector CI/CD

on:
  push:
    branches: [ testing,main,prompt,runtest ]
  pull_request:
    branches: [ testing, main, prompt,runtest ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint the code with flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Run tests and generate coverage report
      - name: Run tests
        run: |
          pip install pytest pytest-asyncio pytest-cov
          pytest --cov=app --cov-report=xml

      # Upload the coverage report as an artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Log in to GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker image (lowercase username)
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/${REPO_OWNER}/python-llm-bias-detector:latest .

      - name: Push Docker image (lowercase username)
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${REPO_OWNER}/python-llm-bias-detector:latest


      # # Build the Docker image and tag it for ghcr.io
      # - name: Build Docker image
      #   run: |
      #     docker build -t ghcr.io/${{ github.repository_owner }}/python-llm-bias-detector:latest .

      # # Push the Docker image to GitHub Container Registry
      # - name: Push Docker image
      #   run: |
      #     docker push ghcr.io/${{ github.repository_owner }}/python-llm-bias-detector:latest
      
